# Generated by Django 5.1.5 on 2025-02-02 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_driver_id_alter_trip_id_alter_truck_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='driver',
            name='name',
            field=models.CharField(default='', max_length=30),
        ),
    ]
