# Generated by Django 5.1.5 on 2025-02-14 16:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_truck_last_updated_truck_latitude_truck_longitude'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip',
            name='destination',
        ),
        migrations.AddField(
            model_name='trip',
            name='route',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='core.route'),
            preserve_default=False,
        ),
    ]
