# Generated by Django 5.1.5 on 2025-02-15 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_trip_end_time_trip_last_latitude_trip_last_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.DateTimeField(),
        ),
    ]
