# Generated by Django 5.1.5 on 2025-02-15 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_trip_end_time_alter_trip_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='trip',
            name='start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
