# Generated by Django 5.1.5 on 2025-02-15 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_alter_trip_end_time_alter_trip_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trip',
            name='status',
            field=models.CharField(choices=[('pending', 'pending'), ('started', 'started'), ('paused', 'paused'), ('resumed', 'resumed'), ('ended', 'ended')], default='pending', max_length=20),
        ),
    ]
