# Generated by Django 5.1.5 on 2025-02-16 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_alter_trip_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='simulation_active',
            field=models.BooleanField(default=False),
        ),
    ]
