# Generated by Django 5.1.5 on 2025-02-16 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_trip_simulation_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='truck',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('in_trip', 'In Trip'), ('maintenance', 'Under Maintenance')], default='available', max_length=20),
        ),
    ]
