# Generated by Django 5.1.5 on 2025-02-24 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='trip',
            name='pause_reason_mechanical',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='trip',
            name='pause_reason_rest',
            field=models.BooleanField(default=False),
        ),
    ]
